-- Create 67 projects from Excel data
-- Customer name = Project name, Type: AI, Status: Active

INSERT INTO projects (id, customer_name, project_name, project_type, status, is_archived, created_at)
VALUES
  (gen_random_uuid(), 'Adapt global studios (AI Assess)', 'Adapt global studios (AI Assess)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Administration (HRS,Hubspot,  Etc)', 'Administration (HRS,Hubspot,  Etc)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'AI and Presell', 'AI and Presell', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Aires (AI Assess RAPID)', 'Aires (AI Assess RAPID)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Einat Asic [Mishki Ram] - SW Discovery', 'Einat Asic [Mishki Ram] - SW Discovery', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Black widow - (signed on nov 25 )', 'Black widow - (signed on nov 25 )', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Black Widow MVP (16.01)', 'Black Widow MVP (16.01)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'BMT', 'BMT', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'CBC (T&M)', 'CBC (T&M)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Ceel', 'Ceel', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Elcam - Delivery', 'Elcam - Delivery', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'FuturePACS assess', 'FuturePACS assess', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'HRS', 'HRS', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Hyp', 'Hyp', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'IAI (POC) - 23 hr', 'IAI (POC) - 23 hr', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'IBI Roeto MVP', 'IBI Roeto MVP', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'IBI searchfund MVP', 'IBI searchfund MVP', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'IBI Transactions MVP', 'IBI Transactions MVP', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Lake (MVP)', 'Lake (MVP)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Mishki Ram - Barak [3.11]', 'Mishki Ram - Barak [3.11]', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Rimon - Mishki Ram - Raam (Water Dev)', 'Rimon - Mishki Ram - Raam (Water Dev)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'OptionUp POC', 'OptionUp POC', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Partner Prod (20 hrs PM)', 'Partner Prod (20 hrs PM)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Patient7 ($125K MVP)', 'Patient7 ($125K MVP)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Paz Gaz', 'Paz Gaz', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Presale', 'Presale', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'ProjectTools ($31K POC)', 'ProjectTools ($31K POC)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'RodRadar', 'RodRadar', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Septier', 'Septier', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'SignetureDX', 'SignetureDX', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Smart Girls PoC', 'Smart Girls PoC', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Subivi (AI Assess)', 'Subivi (AI Assess)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'SuperPharm (BO)', 'SuperPharm (BO)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'SuperPharm (Pharmacy)', 'SuperPharm (Pharmacy)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'SuperPharm (POS)', 'SuperPharm (POS)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Tadiran', 'Tadiran', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Leadbeam (PoC)', 'Leadbeam (PoC)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'GradIT  PoC', 'GradIT  PoC', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Leumit OCR - Presale', 'Leumit OCR - Presale', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Lightship - MVP', 'Lightship - MVP', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Linkme POC', 'Linkme POC', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'BuyerFolio (PoC)', 'BuyerFolio (PoC)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Eduard Technologies (TWO PoCs)', 'Eduard Technologies (TWO PoCs)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Open University', 'Open University', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Seacure ZEN', 'Seacure ZEN', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'ImmuniSense PoC', 'ImmuniSense PoC', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'BIO Catch Discovery', 'BIO Catch Discovery', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'VCOMM POC', 'VCOMM POC', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Investmint POC', 'Investmint POC', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Malmab', 'Malmab', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Averna (assesment)', 'Averna (assesment)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Flexfactor MVP', 'Flexfactor MVP', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Benchmark MVP', 'Benchmark MVP', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Ryvid MVP signed 31/3', 'Ryvid MVP signed 31/3', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'ScyllaDB (sw)', 'ScyllaDB (sw)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Energyby5', 'Energyby5', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'LayerX Assess 9/4', 'LayerX Assess 9/4', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Pandos Assess (8.04)', 'Pandos Assess (8.04)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Seeded Assess (10.4)', 'Seeded Assess (10.4)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'FuturePACS PoC', 'FuturePACS PoC', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'StoreNext', 'StoreNext', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Greywolf AI POC ( signed - 27.4.26)', 'Greywolf AI POC ( signed - 27.4.26)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'DBdude', 'DBdude', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Vivaium - SW Discovery', 'Vivaium - SW Discovery', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'CryptoC (SW)', 'CryptoC (SW)', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Rezora AI Assess 5K', 'Rezora AI Assess 5K', 'AI', 'Active', false, NOW()),
  (gen_random_uuid(), 'Flexible AI Assess (14.4)', 'Flexible AI Assess (14.4)', 'AI', 'Active', false, NOW());

-- Verify
SELECT COUNT(*) as total_projects FROM projects WHERE is_archived = false;
